//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGameLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> PlayId { get; set; }
        public Nullable<int> UserOpinionId { get; set; }
        public System.DateTime Date { get; set; }
        public string CommentDetail { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual UserOpinion UserOpinion { get; set; }
        public virtual Play Play { get; set; }
        public virtual Request Request { get; set; }
        public virtual User User { get; set; }
    }
}
