//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGameLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expansion
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ParentGameId { get; set; }
        public string Description { get; set; }
        public Nullable<int> OwnedById { get; set; }
        public bool AtWork { get; set; }
    
        public virtual Game ParentGame { get; set; }
        public virtual User Owner { get; set; }
    }
}
